// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCujPQ4-3sK4JChM0FdldXMeM3DD-ER5pA',
    appId: '1:1089046799877:web:d991d56d4514e2f0ac5e6c',
    messagingSenderId: '1089046799877',
    projectId: 'mychaty-a8c85',
    authDomain: 'mychaty-a8c85.firebaseapp.com',
    storageBucket: 'mychaty-a8c85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXtDJVARn6_SLwfLKvmnPlgDPgOE-oZBE',
    appId: '1:1089046799877:android:7a7f6015be836258ac5e6c',
    messagingSenderId: '1089046799877',
    projectId: 'mychaty-a8c85',
    storageBucket: 'mychaty-a8c85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDayGePULAZOdC9RwPv8CFl7rJx1jzNIdE',
    appId: '1:1089046799877:ios:8bed593f29ee75f9ac5e6c',
    messagingSenderId: '1089046799877',
    projectId: 'mychaty-a8c85',
    storageBucket: 'mychaty-a8c85.firebasestorage.app',
    iosBundleId: 'com.example.mychaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDayGePULAZOdC9RwPv8CFl7rJx1jzNIdE',
    appId: '1:1089046799877:ios:8bed593f29ee75f9ac5e6c',
    messagingSenderId: '1089046799877',
    projectId: 'mychaty-a8c85',
    storageBucket: 'mychaty-a8c85.firebasestorage.app',
    iosBundleId: 'com.example.mychaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCujPQ4-3sK4JChM0FdldXMeM3DD-ER5pA',
    appId: '1:1089046799877:web:269c7f9b94a1067bac5e6c',
    messagingSenderId: '1089046799877',
    projectId: 'mychaty-a8c85',
    authDomain: 'mychaty-a8c85.firebaseapp.com',
    storageBucket: 'mychaty-a8c85.firebasestorage.app',
  );
}
